name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.2.0
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #
  signature: ^2.0.0
  rxdart: ^0.23.0
  json_annotation: ^3.0.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^0.15.1
  timer_builder: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  test: ^1.6.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/research_package/assets/sounds/A.mp3
    - packages/research_package/assets/sounds/B.mp3
    - packages/research_package/assets/sounds/C.mp3
    - packages/research_package/assets/sounds/D.mp3
    - packages/research_package/assets/sounds/E.mp3
    - packages/research_package/assets/sounds/F.mp3
    - packages/research_package/assets/sounds/G.mp3
    - packages/research_package/assets/sounds/H.mp3
    - packages/research_package/assets/sounds/I.mp3
    - packages/research_package/assets/sounds/J.mp3
    - packages/research_package/assets/sounds/K.mp3
    - packages/research_package/assets/sounds/L.mp3
    - packages/research_package/assets/sounds/M.mp3
    - packages/research_package/assets/sounds/N.mp3
    - packages/research_package/assets/sounds/O.mp3
    - packages/research_package/assets/sounds/P.mp3
    - packages/research_package/assets/sounds/Q.mp3
    - packages/research_package/assets/sounds/R.mp3
    - packages/research_package/assets/sounds/S.mp3
    - packages/research_package/assets/sounds/T.mp3
    - packages/research_package/assets/sounds/U.mp3
    - packages/research_package/assets/sounds/V.mp3
    - packages/research_package/assets/sounds/W.mp3
    - packages/research_package/assets/sounds/X.mp3
    - packages/research_package/assets/sounds/Y.mp3
    - packages/research_package/assets/sounds/Z.mp3
    - assets/sounds/A.mp3
    - assets/sounds/B.mp3
    - assets/sounds/C.mp3
    - assets/sounds/D.mp3
    - assets/sounds/E.mp3
    - assets/sounds/F.mp3
    - assets/sounds/G.mp3
    - assets/sounds/H.mp3
    - assets/sounds/I.mp3
    - assets/sounds/J.mp3
    - assets/sounds/K.mp3
    - assets/sounds/L.mp3
    - assets/sounds/M.mp3
    - assets/sounds/N.mp3
    - assets/sounds/O.mp3
    - assets/sounds/P.mp3
    - assets/sounds/Q.mp3
    - assets/sounds/R.mp3
    - assets/sounds/S.mp3
    - assets/sounds/T.mp3
    - assets/sounds/U.mp3
    - assets/sounds/V.mp3
    - assets/sounds/W.mp3
    - assets/sounds/X.mp3
    - assets/sounds/Y.mp3
    - assets/sounds/Z.mp3
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
